spring:
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # Driud数据源监控配置
    druid:
      web-stat-filter:
        enabled: true
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 10000
          log-slow-sql: true
        config:

      stat-view-servlet:
        enabled: true
        #        访问地址的链接拦截
        url-pattern: /druid/*
        #        是否允许情况统计数据
        reset-enable: false
        login-username: druid
        login-password: 123456
      filters: stat
      #      对web应用的监控
      aop-patterns: com.base.net.xa.controller.*,com.base.net.xa.service.*


# mybatis的配配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    banner: false

jwt-securet: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJpc3MiOiJhdXRoMCJ9.AbIJTDMFc7yUa5MhvcP03nJPyCPzZtQcGEp-zWfOkEE
jwt-expire: 86400000
